### ISSUE TITLE
Ethereum node connection error 

### ISSUE THREAD

**Issue by douglasdeodato** [ethereumproject/mist#51]
#### System information
``````
Version: `Wallet 0.9.1 (Pre Release)`
OS & Version: windows
Node type: `eth/getc(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereumproject/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots
![c22a3788-140b-11e7-9837-bd43e4cda36c](https://user-images.githubusercontent.com/993318/27259766-56ff3a66-5412-11e7-82d3-53c16363c480.png)

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot
![console](https://user-images.githubusercontent.com/993318/27259793-faab648c-5412-11e7-8062-54695bfc5c2a.png)

- Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):
  -   osx: `~/Library/Application Support/Mist/node.log`
  -   windows: `%APPDATA%/Roaming/Mist/node.log`
  -   linux: `~/.config/Mist/node.log`

This folder does not exist in my system Mist.

I just downloaded the last release and (win - upacked folder and I click in : Ethereum Classic Wallet app

someone can help on this? thank you.

**Comment by MaxWave3000** [comment]
Hello. Too long have struggled with this mistake. For about two days. But still got to fix it. The problem is that this version of the wallet downloads the file with the geth, but unable to unzip it. When checking it turned out that the file geth.exe just zero bytes. 
What I did: 
1. Launched wallet and got the error. 
2. Moved to \Roaming\Ethereum Classic Wallet\binaries\Geth. 
3. Manually unzipped arhiv.zip 
4. Put it in a folder called "unpacked".
 5. Put the read-only attribute. 
6. Put the exact time and started the wallet. 
And it worked.

**Comment by sean-thorburn** [comment]
This does indeed solve the problem. Thank you for taking the time to post your solution!

**Comment by curator999** [comment]
Hi. Could you please tell me if you know. I follow your advice but unzipped file show the date 31.12.1969 date modified. Why so? Can it be something that create the node error? 
And last question read-only attribute is .... ?
Please advice.

**Comment by sean-thorburn** [comment]
@curator999 The date doesn't matter. To see the read only attribute - right click a file and click on Properties. At the bottom of the dialog you will see some check-boxes. Make sure the Read Only check-box is ticked.
